package com.glucodes.swarmdoc.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.remember

/**
 * Compose-level localization for SwarmDoc.
 * Since all UI strings are hardcoded in Kotlin (not using Android string resources),
 * this provides translated strings via a CompositionLocal.
 */
data class AppStrings(
    // Home Screen
    val swarmDoc: String = "SwarmDoc",
    val startConsultation: String = "Start Consultation",
    val tapToBeginAssessment: String = "Tap to begin a new patient assessment",
    val diagnostics: String = "Diagnostics",
    val onDeviceVitals: String = "On-device vitals & screening",
    val myPatients: String = "My Patients",
    val patientsLogged: String = "patients logged",
    val communityHealthMap: String = "Community Health Map",
    val allClearInZone: String = "All clear in your zone",
    val outbreakAlert: String = "OUTBREAK ALERT - Tap for details",
    val workersActiveNearYou: String = "workers active near you",
    val todaysFocus: String = "Today's Focus",
    val dos: String = "Do's",
    val donts: String = "Don'ts",
    val basicProcedures: String = "Basic Procedures",

    // Consultation
    val consultation: String = "Consultation",
    val patientDetails: String = "Patient Details",
    val patientNameOptional: String = "Patient Name (optional)",
    val age: String = "Age",
    val years: String = "years",
    val sex: String = "Sex",
    val male: String = "Male",
    val female: String = "Female",
    val other: String = "Other",
    val village: String = "Village",
    val district: String = "District",
    val nextChooseInputMode: String = "Next: Choose Input Mode",
    val howToDescribeSymptoms: String = "How to describe symptoms?",
    val describeByVoice: String = "Describe by Voice",
    val speakSymptomsInYourLang: String = "Speak symptoms in your language",
    val typeSymptoms: String = "Type Symptoms",
    val selectFromSymptomList: String = "Select from symptom list and add notes",
    val capturePhoto: String = "Capture a Photo",
    val woundSkinEyeReport: String = "Wound, skin, eye, or paper report",
    val continueToSymptoms: String = "Continue to Symptoms",
    val selectSymptoms: String = "Select Symptoms",
    val tapAllSymptoms: String = "Tap all symptoms that apply",
    val durationDays: String = "Duration (days)",
    val vitalsOptional: String = "Vitals (optional)",
    val additionalNotes: String = "Additional notes",
    val runDiagnosis: String = "Run Diagnosis",
    val analyzing: String = "Analyzing...",
    val runningDiagnosticAssessment: String = "Running diagnostic assessment",
    val possibleConditions: String = "Possible Conditions",
    val recommendedMedicines: String = "Recommended Medicines",
    val inStock: String = "In Stock",
    val outOfStock: String = "Out of Stock",
    val saveAndContinue: String = "Save and Continue",
    val consultationSaved: String = "Consultation Saved",
    val sosAlertNearestDoctor: String = "SOS - Alert Nearest Doctor",
    val referToPHC: String = "Refer to PHC",
    val shareWithDoctor: String = "Share with Doctor",
    val returnToHome: String = "Return to Home",

    // Community
    val communityHealth: String = "Community Health",
    val villageHealthMemory: String = "Village Health Memory",
    val meshNetworkStatus: String = "Mesh Network Status",
    val peersDiscovered: String = "Peers Discovered",
    val totalMemory: String = "Total Memory",
    val lastSync: String = "Last sync",
    val syncActivePeers: String = "Sync Active Peers",
    val sevenDayEpidemicTimeline: String = "7-Day Epidemic Timeline",
    val activeSymptomClusters: String = "Active Symptom Clusters",
    val noClustersDetected: String = "No active clusters detected in your zone.",
    val outbreakThresholdCrossed: String = "Outbreak Threshold Crossed",

    // SOS
    val emergencyAlerts: String = "Emergency Alerts",

    // Profile Setup
    val profileSetup: String = "Profile Setup",
    val welcomeAshaWorker: String = "Welcome, ASHA Worker!",
    val setupYourProfile: String = "Set up your profile to get started",
    val yourName: String = "Your Name",
    val setPin: String = "Set a 4-digit PIN",
    val completeSetup: String = "Complete Setup",

    // Diagnostics
    val coughScreener: String = "Cough Screener",
    val anemiaEyeCheck: String = "Anemia Eye Check",
    val contactlessVitals: String = "Contactless Vitals",
    val capillaryRefillTest: String = "Capillary Refill Test",
    val startRecording: String = "Start Recording",
    val recording: String = "Recording...",
    val restart: String = "Restart",
    val submitAudio: String = "Submit Audio",
    val rerecord: String = "Re-record",
    val coughIntoMicrophone: String = "Cough into microphone",

    // General
    val back: String = "Back",
    val next: String = "Next",
    val skip: String = "Skip",
    val getStarted: String = "Get Started",
    val fillRequiredFields: String = "Please fill in Age, Sex, and Village to continue",
    val femalePrivacyMode: String = "Female Privacy Mode",
    val communityAlert: String = "Community Alert",
    val acousticCoughDescription: String = "Acoustic ML analysis for respiratory infections",
    val anemiaEyeDescription: String = "Eyelid pallor analysis via smartphone camera",
    val rppgDescription: String = "Contactless vitals from facial micro-color changes",
    val capillaryDescription: String = "Fingernail circulation timing for dehydration",

    // Worker Profile
    val myProfile: String = "My Profile",
    val myPrimaryFocus: String = "My Primary Focus",
    val myCentresStock: String = "My Centre's Stock",
    val updateMedicineAvailability: String = "Update medicine availability",
    val exportAllRecords: String = "Export All Records",
    val downloadAsJson: String = "Download as JSON to device",
    val changeLanguage: String = "Change Language",
    val chooseYourLanguage: String = "Choose Your Language",
)

val Hindi = AppStrings(
    swarmDoc = "स्वार्मडॉक",
    startConsultation = "परामर्श शुरू करें",
    tapToBeginAssessment = "नया रोगी मूल्यांकन शुरू करने के लिए टैप करें",
    diagnostics = "निदान",
    onDeviceVitals = "डिवाइस पर स्वास्थ्य जांच",
    myPatients = "मेरे मरीज़",
    patientsLogged = "मरीज़ दर्ज",
    communityHealthMap = "सामुदायिक स्वास्थ्य मानचित्र",
    allClearInZone = "आपके क्षेत्र में सब ठीक",
    outbreakAlert = "प्रकोप चेतावनी - विवरण के लिए टैप करें",
    workersActiveNearYou = "कार्यकर्ता आपके पास सक्रिय",
    todaysFocus = "आज का फोकस",
    dos = "करें",
    donts = "न करें",
    basicProcedures = "बुनियादी प्रक्रियाएँ",
    consultation = "परामर्श",
    patientDetails = "मरीज़ विवरण",
    patientNameOptional = "मरीज़ का नाम (वैकल्पिक)",
    age = "आयु",
    years = "वर्ष",
    sex = "लिंग",
    male = "पुरुष",
    female = "महिला",
    other = "अन्य",
    village = "गांव",
    district = "जिला",
    nextChooseInputMode = "अगला: इनपुट मोड चुनें",
    howToDescribeSymptoms = "लक्षण कैसे बताएं?",
    describeByVoice = "आवाज़ से बताएं",
    speakSymptomsInYourLang = "अपनी भाषा में लक्षण बोलें",
    typeSymptoms = "लक्षण लिखें",
    selectFromSymptomList = "सूची से चुनें और नोट्स जोड़ें",
    capturePhoto = "फोटो लें",
    woundSkinEyeReport = "घाव, त्वचा, आंख या रिपोर्ट",
    continueToSymptoms = "लक्षणों पर जाएं",
    selectSymptoms = "लक्षण चुनें",
    tapAllSymptoms = "सभी लागू लक्षणों को टैप करें",
    durationDays = "अवधि (दिन)",
    vitalsOptional = "जीवन संकेत (वैकल्पिक)",
    additionalNotes = "अतिरिक्त नोट्स",
    runDiagnosis = "निदान चलाएं",
    analyzing = "विश्लेषण हो रहा है...",
    runningDiagnosticAssessment = "नैदानिक मूल्यांकन चल रहा है",
    possibleConditions = "संभावित स्थितियां",
    recommendedMedicines = "अनुशंसित दवाइयां",
    inStock = "उपलब्ध",
    outOfStock = "अनुपलब्ध",
    saveAndContinue = "सहेजें और जारी रखें",
    consultationSaved = "परामर्श सहेजा गया",
    sosAlertNearestDoctor = "SOS - निकटतम डॉक्टर को सचेत करें",
    referToPHC = "PHC को रेफर करें",
    shareWithDoctor = "डॉक्टर को भेजें",
    returnToHome = "होम पर लौटें",
    communityHealth = "सामुदायिक स्वास्थ्य",
    villageHealthMemory = "गांव स्वास्थ्य मेमोरी",
    meshNetworkStatus = "मेश नेटवर्क स्थिति",
    peersDiscovered = "पीयर खोजे गए",
    totalMemory = "कुल मेमोरी",
    lastSync = "अंतिम सिंक",
    syncActivePeers = "सक्रिय पीयर सिंक करें",
    sevenDayEpidemicTimeline = "7-दिन महामारी समयरेखा",
    activeSymptomClusters = "सक्रिय लक्षण क्लस्टर",
    noClustersDetected = "आपके क्षेत्र में कोई सक्रिय क्लस्टर नहीं।",
    outbreakThresholdCrossed = "प्रकोप सीमा पार",
    emergencyAlerts = "आपातकालीन चेतावनी",
    profileSetup = "प्रोफाइल सेटअप",
    welcomeAshaWorker = "स्वागत है, आशा कार्यकर्ता!",
    setupYourProfile = "शुरू करने के लिए अपनी प्रोफाइल बनाएं",
    yourName = "आपका नाम",
    setPin = "4-अंकों का PIN सेट करें",
    completeSetup = "सेटअप पूरा करें",
    coughScreener = "खांसी स्क्रीनर",
    anemiaEyeCheck = "एनीमिया आंख जांच",
    contactlessVitals = "गैर-संपर्क जांच",
    capillaryRefillTest = "कैपिलरी रिफिल टेस्ट",
    startRecording = "रिकॉर्डिंग शुरू करें",
    recording = "रिकॉर्डिंग...",
    restart = "पुनः आरंभ",
    back = "वापस",
    next = "अगला",
    skip = "छोड़ें",
    getStarted = "शुरू करें",
    fillRequiredFields = "जारी रखने के लिए आयु, लिंग और गांव भरें",
    femalePrivacyMode = "महिला गोपनीयता मोड",
    communityAlert = "सामुदायिक चेतावनी",
    myProfile = "मेरी प्रोफाइल",
    myPrimaryFocus = "मेरा मुख्य फोकस",
    myCentresStock = "मेरे केंद्र का स्टॉक",
    updateMedicineAvailability = "दवा की उपलब्धता अपडेट करें",
    exportAllRecords = "सभी रिकॉर्ड निर्यात करें",
    downloadAsJson = "डिवाइस में JSON के रूप में डाउनलोड करें",
    changeLanguage = "भाषा बदलें",
    chooseYourLanguage = "अपनी भाषा चुनें",
)

val Odia = AppStrings(
    swarmDoc = "ସ୍ୱାର୍ମଡକ୍",
    startConsultation = "ପରାମର୍ଶ ଆରମ୍ଭ କରନ୍ତୁ",
    tapToBeginAssessment = "ନୂଆ ରୋଗୀ ମୂଲ୍ୟାଙ୍କନ ଆରମ୍ଭ କରିବାକୁ ଟ୍ୟାପ୍ କରନ୍ତୁ",
    diagnostics = "ନିଦାନ",
    onDeviceVitals = "ଡିଭାଇସରେ ସ୍ୱାସ୍ଥ୍ୟ ଯାଞ୍ଚ",
    myPatients = "ମୋ ରୋଗୀ",
    patientsLogged = "ରୋଗୀ ରେକର୍ଡ",
    communityHealthMap = "ସାମୁଦାୟିକ ସ୍ୱାସ୍ଥ୍ୟ ମାନଚିତ୍ର",
    allClearInZone = "ଆପଣଙ୍କ ଜୋନରେ ସବୁ ଠିକ୍",
    outbreakAlert = "ପ୍ରକୋପ ସତର୍କତା - ବିବରଣୀ ପାଇଁ ଟ୍ୟାପ୍ କରନ୍ତୁ",
    workersActiveNearYou = "କର୍ମୀ ଆପଣଙ୍କ ପାଖରେ ସକ୍ରିୟ",
    todaysFocus = "ଆଜିର ଫୋକସ୍",
    dos = "କରନ୍ତୁ",
    donts = "କରନ୍ତୁ ନାହିଁ",
    basicProcedures = "ମୌଳିକ ପ୍ରକ୍ରିୟା",
    consultation = "ପରାମର୍ଶ",
    patientDetails = "ରୋଗୀ ବିବରଣୀ",
    patientNameOptional = "ରୋଗୀ ନାମ (ଐଚ୍ଛିକ)",
    age = "ବୟସ",
    years = "ବର୍ଷ",
    sex = "ଲିଙ୍ଗ",
    male = "ପୁରୁଷ",
    female = "ମହିଳା",
    other = "ଅନ୍ୟ",
    village = "ଗ୍ରାମ",
    district = "ଜିଲ୍ଲା",
    nextChooseInputMode = "ପରବର୍ତ୍ତୀ: ଇନପୁଟ ମୋଡ୍ ବାଛନ୍ତୁ",
    howToDescribeSymptoms = "ଲକ୍ଷଣ କିପରି ବର୍ଣ୍ଣନା କରିବେ?",
    describeByVoice = "ସ୍ୱରରେ କୁହନ୍ତୁ",
    speakSymptomsInYourLang = "ଆପଣଙ୍କ ଭାଷାରେ ଲକ୍ଷଣ କୁହନ୍ତୁ",
    typeSymptoms = "ଲକ୍ଷଣ ଟାଇପ୍ କରନ୍ତୁ",
    selectFromSymptomList = "ତାଲିକାରୁ ବାଛନ୍ତୁ ଏବଂ ନୋଟ୍ ଯୋଡନ୍ତୁ",
    capturePhoto = "ଫଟୋ ନିଅନ୍ତୁ",
    woundSkinEyeReport = "ଘା, ଚମ, ଆଖି ବା ରିପୋର୍ଟ",
    continueToSymptoms = "ଲକ୍ଷଣକୁ ଯାଆନ୍ତୁ",
    selectSymptoms = "ଲକ୍ଷଣ ବାଛନ୍ତୁ",
    tapAllSymptoms = "ସମସ୍ତ ଲାଗୁ ଲକ୍ଷଣ ଟ୍ୟାପ୍ କରନ୍ତୁ",
    durationDays = "ଅବଧି (ଦିନ)",
    vitalsOptional = "ଜୀବନ ଚିହ୍ନ (ଐଚ୍ଛିକ)",
    additionalNotes = "ଅତିରିକ୍ତ ନୋଟ୍",
    runDiagnosis = "ନିଦାନ ଚଲାନ୍ତୁ",
    analyzing = "ବିଶ୍ଳେଷଣ ହେଉଛି...",
    runningDiagnosticAssessment = "ନିଦାନ ମୂଲ୍ୟାଙ୍କନ ଚାଲିଛି",
    possibleConditions = "ସମ୍ଭାବ୍ୟ ରୋଗ",
    recommendedMedicines = "ସୁପାରିଶ ଔଷଧ",
    inStock = "ଉପଲବ୍ଧ",
    outOfStock = "ଅନୁପଲବ୍ଧ",
    saveAndContinue = "ସଞ୍ଚୟ କରନ୍ତୁ ଏବଂ ଜାରି ରଖନ୍ତୁ",
    consultationSaved = "ପରାମର୍ଶ ସଞ୍ଚୟ ହୋଇଛି",
    sosAlertNearestDoctor = "SOS - ନିକଟତମ ଡାକ୍ତରଙ୍କୁ ସତର୍କ କରନ୍ତୁ",
    referToPHC = "PHC କୁ ରେଫର କରନ୍ତୁ",
    shareWithDoctor = "ଡାକ୍ତରଙ୍କୁ ପଠାନ୍ତୁ",
    returnToHome = "ହୋମକୁ ଫେରନ୍ତୁ",
    communityHealth = "ସାମୁଦାୟିକ ସ୍ୱାସ୍ଥ୍ୟ",
    villageHealthMemory = "ଗ୍ରାମ ସ୍ୱାସ୍ଥ୍ୟ ମେମୋରୀ",
    meshNetworkStatus = "ମେଶ ନେଟୱାର୍କ ସ୍ଥିତି",
    peersDiscovered = "ପିୟର ଖୋଜି ହୋଇଛି",
    totalMemory = "ମୋଟ ମେମୋରୀ",
    lastSync = "ଶେଷ ସିଙ୍କ",
    syncActivePeers = "ସକ୍ରିୟ ପିୟର ସିଙ୍କ କରନ୍ତୁ",
    sevenDayEpidemicTimeline = "7-ଦିନ ମହାମାରୀ ସମୟରେଖା",
    activeSymptomClusters = "ସକ୍ରିୟ ଲକ୍ଷଣ କ୍ଲଷ୍ଟର",
    noClustersDetected = "ଆପଣଙ୍କ ଜୋନରେ କୌଣସି ସକ୍ରିୟ କ୍ଲଷ୍ଟର ନାହିଁ।",
    outbreakThresholdCrossed = "ପ୍ରକୋପ ସୀମା ପାର",
    emergencyAlerts = "ଜରୁରୀ ସତର୍କତା",
    profileSetup = "ପ୍ରୋଫାଇଲ ସେଟଅପ",
    welcomeAshaWorker = "ସ୍ୱାଗତ, ଆଶା କର୍ମୀ!",
    setupYourProfile = "ଆରମ୍ଭ କରିବାକୁ ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ ତିଆରି କରନ୍ତୁ",
    yourName = "ଆପଣଙ୍କ ନାମ",
    setPin = "4-ଅଙ୍କ PIN ସେଟ କରନ୍ତୁ",
    completeSetup = "ସେଟଅପ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ",
    coughScreener = "କାଶ ସ୍କ୍ରୀନର",
    anemiaEyeCheck = "ରକ୍ତହୀନତା ଆଖି ଯାଞ୍ଚ",
    contactlessVitals = "ଅସ୍ପର୍ଶ ଯାଞ୍ଚ",
    capillaryRefillTest = "କ୍ୟାପିଲାରୀ ରିଫିଲ ଟେଷ୍ଟ",
    startRecording = "ରେକର୍ଡିଂ ଆରମ୍ଭ କରନ୍ତୁ",
    recording = "ରେକର୍ଡିଂ...",
    restart = "ପୁନଃ ଆରମ୍ଭ",
    back = "ପଛକୁ",
    next = "ପରବର୍ତ୍ତୀ",
    skip = "ଛାଡନ୍ତୁ",
    getStarted = "ଆରମ୍ଭ କରନ୍ତୁ",
    fillRequiredFields = "ଜାରି ରଖିବାକୁ ବୟସ, ଲିଙ୍ଗ ଏବଂ ଗ୍ରାମ ପୂରଣ କରନ୍ତୁ",
    femalePrivacyMode = "ମହିଳା ଗୋପନୀୟତା ମୋଡ",
    communityAlert = "ସାମୁଦାୟିକ ସତର୍କତା",
    myProfile = "ମୋ ପ୍ରୋଫାଇଲ୍",
    myPrimaryFocus = "ମୋର ମୁଖ୍ୟ ଧ୍ୟାନ",
    myCentresStock = "ମୋ କେନ୍ଦ୍ରର ଷ୍ଟକ୍",
    updateMedicineAvailability = "ଔଷଧ ଉପଲବ୍ଧତା ଅପଡେଟ୍ କରନ୍ତୁ",
    exportAllRecords = "ସମସ୍ତ ରେକର୍ଡ ଏକ୍ସପୋର୍ଟ କରନ୍ତୁ",
    downloadAsJson = "ଡିଭାଇସକୁ JSON ଭାବରେ ଡାଉନଲୋଡ୍ କରନ୍ତୁ",
    changeLanguage = "ଭାଷା ପରିବର୍ତ୍ତନ କରନ୍ତୁ",
    chooseYourLanguage = "ଆପଣଙ୍କ ଭାଷା ବାଛନ୍ତୁ",
)

val Telugu = AppStrings(
    swarmDoc = "స్వార్మ్‌డాక్",
    startConsultation = "సంప్రదింపు ప్రారంభించండి",
    tapToBeginAssessment = "కొత్త రోగి అంచనా ప్రారంభించడానికి ట్యాప్ చేయండి",
    diagnostics = "రోగ నిర్ధారణ",
    onDeviceVitals = "పరికరంలో ఆరోగ్య పరీక్ష",
    myPatients = "నా రోగులు",
    patientsLogged = "రోగులు నమోదు",
    communityHealthMap = "సామాజిక ఆరోగ్య మ్యాప్",
    allClearInZone = "మీ ప్రాంతంలో అంతా బాగానే ఉంది",
    outbreakAlert = "అంటువ్యాధి హెచ్చరిక - వివరాల కోసం ట్యాప్ చేయండి",
    workersActiveNearYou = "కార్యకర్తలు మీ సమీపంలో సక్రియంగా ఉన్నారు",
    todaysFocus = "ఈ రోజు ఫోకస్",
    dos = "చేయాల్సినవి",
    donts = "చేయకూడనివి",
    basicProcedures = "ప్రాథమిక ప్రక్రియలు",
    consultation = "సంప్రదింపు",
    patientDetails = "రోగి వివరాలు",
    patientNameOptional = "రోగి పేరు (ఐచ్ఛికం)",
    age = "వయసు",
    years = "సంవత్సరాలు",
    sex = "లింగం",
    male = "మగ",
    female = "ఆడ",
    other = "ఇతర",
    village = "గ్రామం",
    district = "జిల్లా",
    nextChooseInputMode = "తదుపరి: ఇన్‌పుట్ మోడ్ ఎంచుకోండి",
    howToDescribeSymptoms = "లక్షణాలను ఎలా వివరించాలి?",
    describeByVoice = "మాటద్వారా చెప్పండి",
    speakSymptomsInYourLang = "మీ భాషలో లక్షణాలు చెప్పండి",
    typeSymptoms = "లక్షణాలు టైప్ చేయండి",
    selectFromSymptomList = "జాబితా నుండి ఎంచుకోండి మరియు నోట్స్ జోడించండి",
    capturePhoto = "ఫోటో తీయండి",
    woundSkinEyeReport = "గాయం, చర్మం, కన్ను లేదా రిపోర్ట్",
    continueToSymptoms = "లక్షణాలకు కొనసాగండి",
    selectSymptoms = "లక్షణాలు ఎంచుకోండి",
    tapAllSymptoms = "వర్తించే అన్ని లక్షణాలను ట్యాప్ చేయండి",
    durationDays = "వ్యవధి (రోజులు)",
    vitalsOptional = "ప్రాణ సంకేతాలు (ఐచ్ఛికం)",
    additionalNotes = "అదనపు నోట్స్",
    runDiagnosis = "నిర్ధారణ చేయండి",
    analyzing = "విశ్లేషిస్తోంది...",
    runningDiagnosticAssessment = "రోగ నిర్ధారణ అంచనా జరుగుతోంది",
    possibleConditions = "సాధ్యమైన పరిస్థితులు",
    recommendedMedicines = "సూచించిన మందులు",
    inStock = "అందుబాటులో ఉంది",
    outOfStock = "అందుబాటులో లేదు",
    saveAndContinue = "సేవ్ చేసి కొనసాగించండి",
    consultationSaved = "సంప్రదింపు సేవ్ చేయబడింది",
    sosAlertNearestDoctor = "SOS - సమీపంలోని వైద్యుడిని హెచ్చరించండి",
    referToPHC = "PHC కి రిఫర్ చేయండి",
    shareWithDoctor = "వైద్యుడికి పంపండి",
    returnToHome = "హోమ్‌కు తిరిగి వెళ్ళండి",
    communityHealth = "సామాజిక ఆరోగ్యం",
    villageHealthMemory = "గ్రామ ఆరోగ్య మెమరీ",
    meshNetworkStatus = "మెష్ నెట్‌వర్క్ స్థితి",
    peersDiscovered = "పీర్‌లు కనుగొనబడ్డారు",
    totalMemory = "మొత్తం మెమరీ",
    lastSync = "చివరి సింక్",
    syncActivePeers = "సక్రియ పీర్‌లను సింక్ చేయండి",
    sevenDayEpidemicTimeline = "7-రోజుల అంటువ్యాధి కాలరేఖ",
    activeSymptomClusters = "సక్రియ లక్షణ క్లస్టర్‌లు",
    noClustersDetected = "మీ ప్రాంతంలో సక్రియ క్లస్టర్‌లు లేవు.",
    outbreakThresholdCrossed = "అంటువ్యాధి పరిమితి దాటింది",
    emergencyAlerts = "అత్యవసర హెచ్చరికలు",
    profileSetup = "ప్రొఫైల్ సెటప్",
    welcomeAshaWorker = "స్వాగతం, ఆశా కార్యకర్త!",
    setupYourProfile = "ప్రారంభించడానికి మీ ప్రొఫైల్‌ను సెటప్ చేయండి",
    yourName = "మీ పేరు",
    setPin = "4-అంకెల PIN సెట్ చేయండి",
    completeSetup = "సెటప్ పూర్తి చేయండి",
    coughScreener = "దగ్గు స్క్రీనర్",
    anemiaEyeCheck = "రక్తహీనత కన్ను పరీక్ష",
    contactlessVitals = "సంపర్క రహిత పరీక్ష",
    capillaryRefillTest = "కేశనాళిక రీఫిల్ టెస్ట్",
    startRecording = "రికార్డింగ్ ప్రారంభించండి",
    recording = "రికార్డ్ అవుతోంది...",
    restart = "పునః ప్రారంభించండి",
    back = "వెనుకకు",
    next = "తదుపరి",
    skip = "దాటవేయి",
    getStarted = "ప్రారంభించండి",
    fillRequiredFields = "కొనసాగించడానికి వయస్సు, లింగం మరియు గ్రామం నింపండి",
    femalePrivacyMode = "మహిళా గోప్యతా మోడ్",
    communityAlert = "సామాజిక హెచ్చరిక",
    myProfile = "నా ప్రొఫైల్",
    myPrimaryFocus = "నా ప్రాథమిక ఫోకస్",
    myCentresStock = "నా కేంద్రం స్టాక్",
    updateMedicineAvailability = "మందుల లభ్యతను నవీకరించండి",
    exportAllRecords = "అన్ని రికార్డులను ఎగుమతి చేయండి",
    downloadAsJson = "పరికరానికి JSON గా డౌన్‌లోడ్ చేయండి",
    changeLanguage = "భాషను మార్చండి",
    chooseYourLanguage = "మీ భాషను ఎంచుకోండి",
)

val Bengali = AppStrings(
    swarmDoc = "স্বার্মডক",
    startConsultation = "পরামর্শ শুরু করুন",
    tapToBeginAssessment = "নতুন রোগী মূল্যায়ন শুরু করতে ট্যাপ করুন",
    diagnostics = "রোগ নির্ণয়",
    onDeviceVitals = "ডিভাইসে স্বাস্থ্য পরীক্ষা",
    myPatients = "আমার রোগী",
    patientsLogged = "রোগী নথিভুক্ত",
    communityHealthMap = "সম্প্রদায় স্বাস্থ্য মানচিত্র",
    allClearInZone = "আপনার এলাকায় সব ঠিক আছে",
    outbreakAlert = "প্রাদুর্ভাব সতর্কতা - বিবরণের জন্য ট্যাপ করুন",
    workersActiveNearYou = "কর্মীরা আপনার কাছে সক্রিয়",
    todaysFocus = "আজকের ফোকাস",
    dos = "করুন",
    donts = "করবেন না",
    basicProcedures = "মৌলিক পদ্ধতি",
    consultation = "পরামর্শ",
    patientDetails = "রোগীর বিবরণ",
    patientNameOptional = "রোগীর নাম (ঐচ্ছিক)",
    age = "বয়স",
    years = "বছর",
    sex = "লিঙ্গ",
    male = "পুরুষ",
    female = "মহিলা",
    other = "অন্যান্য",
    village = "গ্রাম",
    district = "জেলা",
    nextChooseInputMode = "পরবর্তী: ইনপুট মোড বেছে নিন",
    howToDescribeSymptoms = "লক্ষণ কিভাবে বর্ণনা করবেন?",
    describeByVoice = "কন্ঠে বলুন",
    speakSymptomsInYourLang = "আপনার ভাষায় লক্ষণ বলুন",
    typeSymptoms = "লক্ষণ টাইপ করুন",
    selectFromSymptomList = "তালিকা থেকে বেছে নিন এবং নোট যোগ করুন",
    capturePhoto = "ছবি তুলুন",
    woundSkinEyeReport = "ক্ষত, ত্বক, চোখ বা রিপোর্ট",
    continueToSymptoms = "লক্ষণে যান",
    selectSymptoms = "লক্ষণ বেছে নিন",
    tapAllSymptoms = "সমস্ত প্রযোজ্য লক্ষণ ট্যাপ করুন",
    durationDays = "সময়কাল (দিন)",
    vitalsOptional = "প্রাণ সংকেত (ঐচ্ছিক)",
    additionalNotes = "অতিরিক্ত নোট",
    runDiagnosis = "নির্ণয় চালান",
    analyzing = "বিশ্লেষণ হচ্ছে...",
    runningDiagnosticAssessment = "নির্ণয় মূল্যায়ন চলছে",
    possibleConditions = "সম্ভাব্য রোগ",
    recommendedMedicines = "প্রস্তাবিত ওষুধ",
    inStock = "মজুদে আছে",
    outOfStock = "মজুদে নেই",
    saveAndContinue = "সংরক্ষণ করুন ও চালিয়ে যান",
    consultationSaved = "পরামর্শ সংরক্ষিত",
    sosAlertNearestDoctor = "SOS - নিকটতম ডাক্তারকে সতর্ক করুন",
    referToPHC = "PHC-তে রেফার করুন",
    shareWithDoctor = "ডাক্তারকে পাঠান",
    returnToHome = "হোমে ফিরুন",
    communityHealth = "সম্প্রদায় স্বাস্থ্য",
    villageHealthMemory = "গ্রাম স্বাস্থ্য মেমরি",
    meshNetworkStatus = "মেশ নেটওয়ার্ক অবস্থা",
    peersDiscovered = "পিয়ার পাওয়া গেছে",
    totalMemory = "মোট মেমরি",
    lastSync = "শেষ সিঙ্ক",
    syncActivePeers = "সক্রিয় পিয়ার সিঙ্ক করুন",
    sevenDayEpidemicTimeline = "7-দিনের মহামারী সময়রেখা",
    activeSymptomClusters = "সক্রিয় লক্ষণ ক্লাস্টার",
    noClustersDetected = "আপনার এলাকায় কোনো সক্রিয় ক্লাস্টার নেই।",
    outbreakThresholdCrossed = "প্রাদুর্ভাব সীমা অতিক্রান্ত",
    emergencyAlerts = "জরুরি সতর্কতা",
    profileSetup = "প্রোফাইল সেটআপ",
    welcomeAshaWorker = "স্বাগতম, আশা কর্মী!",
    setupYourProfile = "শুরু করতে আপনার প্রোফাইল তৈরি করুন",
    yourName = "আপনার নাম",
    setPin = "4-সংখ্যার PIN সেট করুন",
    completeSetup = "সেটআপ সম্পূর্ণ করুন",
    coughScreener = "কাশি স্ক্রিনার",
    anemiaEyeCheck = "রক্তস্বল্পতা চোখ পরীক্ষা",
    contactlessVitals = "সংস্পর্শহীন পরীক্ষা",
    capillaryRefillTest = "ক্যাপিলারি রিফিল টেস্ট",
    startRecording = "রেকর্ডিং শুরু করুন",
    recording = "রেকর্ড হচ্ছে...",
    restart = "পুনরায় শুরু",
    back = "পিছনে",
    next = "পরবর্তী",
    skip = "এড়িয়ে যান",
    getStarted = "শুরু করুন",
    fillRequiredFields = "চালিয়ে যেতে বয়স, লিঙ্গ এবং গ্রাম পূরণ করুন",
    femalePrivacyMode = "মহিলা গোপনীয়তা মোড",
    communityAlert = "সম্প্রদায় সতর্কতা",
    myProfile = "আমার প্রোফাইল",
    myPrimaryFocus = "আমার প্রধান লক্ষ্য",
    myCentresStock = "আমার কেন্দ্রের স্টক",
    updateMedicineAvailability = "ওষুধের প্রাপ্যতা আপডেট করুন",
    exportAllRecords = "সমস্ত রেকর্ড এক্সপোর্ট করুন",
    downloadAsJson = "ডিভাইসে JSON হিসেবে ডাউনলোড করুন",
    changeLanguage = "ভাষা পরিবর্তন করুন",
    chooseYourLanguage = "আপনার ভাষা বেছে নিন",
)

/**
 * CompositionLocal providing the current localized strings.
 */
val LocalStrings = compositionLocalOf { AppStrings() }

fun getStringsForLanguage(langCode: String): AppStrings = when (langCode) {
    "hi" -> Hindi
    "or" -> Odia
    "te" -> Telugu
    "bn" -> Bengali
    else -> AppStrings() // English default
}

@Composable
fun ProvideLocalizedStrings(
    languageCode: String,
    content: @Composable () -> Unit
) {
    val strings = remember(languageCode) { getStringsForLanguage(languageCode) }
    CompositionLocalProvider(LocalStrings provides strings) {
        content()
    }
}
